import json
import os

videos = [
  {"slug": "vid-01", "title": "শুধু একটি ওয়েবসাইট তৈরি করাই যথেষ্ট নয়—তৈরি করুন এমন একটি ব্র্যান্ড...", "label": "Animation Reels", "visual": "video", "categories": ["video-editing", "motion-animation"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/fLQB8PC1KUQ?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-02", "title": "Motion and Animation", "label": "Animation Reels", "visual": "video", "categories": ["video-editing", "motion-animation"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/t-EGTUtpfpI?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-03", "title": "Subedar Squad Official Jersey Reveal 2026", "label": "Animation Reels", "visual": "video", "categories": ["video-editing", "motion-animation"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/STPkXbqavVw?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-04", "title": "Eid Al-Adha 2026 Animated Greetings", "label": "Animation Reels", "visual": "video", "categories": ["video-editing", "motion-animation"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/l3v-xK5Qi1M?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-05", "title": "অক্ষর যখন কথা বলে, আর টাইপোগ্রাফি রূপ নেয় চরিত্রে!", "label": "Animation", "visual": "video", "categories": ["video-editing", "motion-animation"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/4lltRHmVmMg", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-06", "title": "ভ্লাদ ড্রাকুলার শেষ পরিণতি ও উসমানীয়দের ভয়ংকর প্রতিশোধ", "label": "Storytelling Reels", "visual": "video", "categories": ["video-editing", "editorial-storytelling"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/vyN0xgrHyqg?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-07", "title": "জ্ঞানের নেশায় কিংবা ক্ষমতার লোভে আমরা কি নিজেদের বিবেকের কাছেই হেরে যাচ্ছি?", "label": "Storytelling Reels", "visual": "video", "categories": ["video-editing", "editorial-storytelling"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/nB0vEmBFtys?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-08", "title": "যা আমরা অপছন্দ করি, তাতেই হয়তো কল্যাণ লুকিয়ে আছে! - Ibn Arabi", "label": "Islamic Voiceover Reels", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/QvNIu3QBuVI?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-09", "title": "Ertugrul & Ibn Arabi Emotional Scene | Bangla Voice Dubbing", "label": "Dawah Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/VLNf7V1GcYg", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-10", "title": "The Rime of the Ancient Mariner - Bangla Summary & Theme", "label": "Literary Storytelling", "visual": "video", "categories": ["video-editing", "editorial-storytelling"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/xIIw2TEnoFI", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-11", "title": "শৈশবে যারা ছিল ভাইয়ের মতো, তারাই কীভাবে হয়ে উঠলো সবচেয়ে চরম শত্রু? Vlad and Mehmed", "label": "Historical Storytelling", "visual": "video", "categories": ["video-editing", "editorial-storytelling"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/7L65UNyTI2s", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"], "featured": True},
  {"slug": "vid-12", "title": "সূরা হাশরের শেষ তিন আয়াত | চমৎকার তেলাওয়াত", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/TW61YcXNDY4", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-13", "title": "সবর– আল্লাহ ধৈর্যশীলদের সাথেই আছেন | Patience in Light of the Qur’an", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/SVEHbcQydfo", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-14", "title": "তাকবীরে তাশরিক | Takbeer e Tashreeq", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/DGNQbVDqGms", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-15", "title": "Surah Fatihaa | Arabic Calligraphy with Bangla translation", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner", "calligraphy-namelipi"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/ez3bufGb1SM", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-16", "title": "Surah Kafirun with Bangla subtitle", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/RmsyRTy_n_4", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-17", "title": "গুনাহে জারিয়া | Think before sharing any post", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/jDG74YsWlmU", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-18", "title": "Surah Ankabut 56-58 | Abdul Rahman Mossad", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/i-GND8SQiBU", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-19", "title": "সূরা কাহফ: ১০৭-১০১০", "label": "Islamic Videos", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtu.be/yPPJHDB0aeg", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-20", "title": "আরাফার রোজার ফজিলত ও দোয়া", "label": "Islamic Reels", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/u_eIZk-viEU?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-21", "title": "Sura Saf: Ayah- 13", "label": "Islamic Reels", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/wF1Ul8slgAY?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]},
  {"slug": "vid-22", "title": "কোরবানির পশুর প্রতিটি পশমের বদলে সওয়াব !", "label": "Islamic Reels", "visual": "video", "categories": ["video-editing", "islamic-corner"], "status": "Published", "video": True, "videoUrl": "https://youtube.com/shorts/2i9edLQDbEg?feature=share", "platform": "YouTube", "tools": ["Premiere Pro", "CapCut"]}
]

os.makedirs("data", exist_ok=True)
js_content = "window.videoArchive = " + json.dumps(videos, indent=2, ensure_ascii=False) + ";"

with open("data/videos.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("Video data injected successfully into data/videos.js")
